### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by SpielenmitLili** [revoX-Development/Germanhostpresence#1]
Ein Readme hinzufügen in dem erklärt ist, wie man das in gängigen Browsern wie Firefox oder Chrome importieren kann?

**Comment by bastianleicht** [comment]
Hi, die Presence ist ein Addon für PreMiD. Hier ein link dazu, wie man diese Importieren kann.
https://docs.premid.app/en/dev/presence#loading-the-presence

**Comment by SpielenmitLili** [comment]
Ja, das war als ein "Feature Request" gedacht. Dass man den Link auch im Readme erwähnt, sodass alle direkt wissen wie man das einstellt.

**Comment by revoX-Development** [comment]
Wird sofort erledigt
